### PR TITLE
Performance boost, code rewrite

### PR DESCRIPTION
**Pull request by SmallJoker**
This pull contains
- Coding style like in the Linux kernel: https://www.kernel.org/doc/Documentation/CodingStyle
- Visual C# 2010 Express compatible -> removed NuGet and its packets
- Faster (?) method to read colors.txt
- New `"init"` parse code ~~[needs testing]~~ :white_check_mark:
- Automatically optimize bitmap before saving

TODO: Extend README.md

### CODE REVIEW

**Comment by alexyorke** [comment]
That looks great, thanks! We really appreciate your help with this, thank you very much

**Comment by SmallJoker** [comment]
No problem but it's strange that you aven't said anything about my changes.
I see you made some commits which reverted parts of my changes and sometimes it also converted the tabs back to spaces, which is kinda annoying.

**Comment by alexyorke** [comment]
Sorry, I'm fairly new to getting pull requests so I'm not sure what the protocol is for saying things about changes. The tabs were converted back to spaces automatically; is there a VS 2015 configuration that I can use to keep it on tabs? Thanks!

**Comment by SmallJoker** [comment]
You can change the coding style in `Options` menu -> `Text-Editor` box -> `C#` -> `Tabstopps`
There, I have the settings "Intelligent" and "Keep tabstops" checked  - I think this is simiar for newer versions.
In the sub-section `Formatting` are several settings about new lines and spaces, it might be helpful to look at them.

**Pull request merged**
